eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8760
spring:
  application:
    name: config
  datasource:
    name: nxDatasource
    url: jdbc:mysql://192.168.3.27:19103/nxdb
    username: nxhquser
    password: nxhqpass
    driver-class-name: com.mysql.jdbc.Driver
